#CC := arm-linux-gnueabi-gcc
CC := gcc

DFUSE_BASE := /home/nicolas/workspace/C/adbfuse/
BIN := df_device
SRC := df_io.c \
       df_device.c \
       df_data_types.c \
       df_protocol.c

CFLAGS += `pkg-config fuse --cflags`
CFLAGS += -O0 -g -Wall -Wextra -Werror
CFLAGS += -D_GNU_SOURCE
#CFLAGS += -static
LDFLAGS += -rdynamic

OBJ = $(SRC:.c=.o)
all:$(BIN)

VPATH := $(DFUSE_BASE)/src/

$(BIN):$(OBJ)
	$(CC) $^ -o $@ $(CFLAGS) $(LDFLAGS)

mrproper:
	rm -f df_device
