#CC := arm-linux-gnueabi-gcc
CC := gcc

DFUSE_BASE := /home/nicolas/workspace/C/adbfuse/
BIN := df_device
SRC := df_io.c \
       df_device.c\
       df_data_types.c\
       df_protocol.c

CFLAGS += `pkg-config fuse --cflags` -Wall -O0 -g -Wextra -Werror
CFLAGS += -D_GNU_SOURCE -static

OBJ = $(SRC:.c=.o)
all:$(BIN)

VPATH := $(DFUSE_BASE)/src/

$(BIN):$(SRC)
	$(CC) $^ -o $@ $(CFLAGS) $(LDFLAGS)

mrproper:
	rm -f df_device
